apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    metadata:
      name: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2

  selector:
    matchLabels:
      app: nginx
