apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  template:
    metadata:
      name: database
    spec:
      containers:
        - name: rs
          image: redis
  replicas: 3

  selector:
    matchLabels:
      app: database
